#define MAX_WORD 15

enum keyw_t {OPEN_BRACES, CLOSE_BRACES, OPEN_PAREN,
	CLOSE_PAREN, CONST, RETURN, IDEN, SPACE,
	OPEN_BRACKETS, CLOSE_BRACKETS,ASTS, MINUS
	,COLON, SEMI_COLON, PLUS, DIVISION, MOD, QUOTES,
	SINGLE_QUOTES, TAB, WHITESPACE, INT, DECIMAL, LONG, SHORT
};

struct token{
	char tk[MAX_WORD];
	enum keyw_t type;
};
